config/routes.rb
Stroimarket::Application.routes.draw do

  devise_for :users

  root 'home#index'

  namespace :admin do
    root to: :index

    resources :products do
      get :custom_category_fields, on: :collection
      get :manufacturer_field, on: :collection

      resources :offers, except: [:index, :show]
    end

    resources :articles do
      post :update_position, on: :collection
    end

    resources :users do
      resources :store_profiles, except: [:index]
    end
    resources :store_profiles, only: [:index]

    resources :categories do
      post :update_position, on: :collection
    end

    resources :service_categories do
      post :update_position, on: :collection
    end

    resources :manufacturers
    resources :services
    resources :posts
  end

  namespace :api do
    resources :categories,          only: [:index, :show],  defaults: {format: :json}

    resources :stores,              only: [:index, :show],  defaults: {format: :json} do
      get :services, on: :member
    end

    resources :products,            only: [:show],          defaults: {format: :json} do
      get :popular, on: :collection
    end

    resources :service_categories,  only: [:index],         defaults: {format: :json}
    resources :services,            only: [:index, :show],  defaults: {format: :json}
    resources :posts,               only: [:index, :show],  defaults: {format: :json}
    resources :articles,            only: [:index, :show],  defaults: {format: :json}
    resources :manufacturers,       only: [:index, :show],  defaults: {format: :json}
    resources :search,              only: [:show],          defaults: {format: :json}
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

end

app/models/service.rb
class Service
  include Mongoid::Document
  include Mongoid::Search
  include Mongoid::Timestamps
  include Content
  include ProductFiles

  belongs_to :service_category
  belongs_to :user

  field :price, type: Integer
  field :views, type: Integer, default: 0

  search_in :title

  validates :service_category_id, :presence => true
  validates :user_id, :presence => true

  def as_json_for_catalog
    options = {
      except: [:_id, :_keywords, :service_category_id, :product_images],
      include: {
        service_category: {
          methods: [:slug],
          only: [
            :_id,
            :slug,
            :title
          ]
        },
        user: {
          only: [:store_profile],
          include: {
            store_profile: {
              only: [
                :slug,
                :name,
                :phone,
                :site,
                :email
              ]
            }
          }
        },
        images: {
          only: [
            :file,
            :title
          ]
        }
      }
    }

    return serializable_hash(options)
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < AdminController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    if current_user.admin?
      @services = Service.all.page(params[:page])
    else
      @services = current_user.services.page(params[:page])
    end
    authorize @services
  end

  def show
  end

  def new
    if current_user.admin?
      @service = Service.new
    else
      @service = current_user.services.new
    end
    authorize @service
  end

  def edit
  end

  def create
    if current_user.admin?
      @service = Service.new(service_params)
    else
      @service = current_user.services.new(service_params)
    end
    authorize @service

    if @service.save
      redirect_to admin_service_path(@service), notice: 'Услуга создана'
    else
      render action: 'new'
    end
  end

  def update
    if @service.update(service_params)
      redirect_to admin_service_path(@service), notice: 'Услуга обновлена'
    else
      render action: 'edit'
    end
  end

  def destroy
    @service.destroy
    redirect_to admin_services_path
  end

  private
    def set_service
      @service = Service.find(params[:id])
      authorize @service
    end

    def service_params
      params.require(:service).permit(
        :title,
        :intro,
        :body,
        :cover,
        :remove_cover,
        :service_category_id,
        :user_id,
        :price,
        images_attributes: [
          :id,
          :title,
          :file,
          :_destroy
        ]
      )
    end
end

app/controllers/api/services_controller.rb
class Api::ServicesController < ApplicationController
  respond_to :json

  def index
    services = Service.all
    respond_with services,
      except: [:body, :_keywords, :cover_filename, :user_id],
      include: {
        user: {
          only: [:store_profile],
          include: {
            store_profile: {
              only: [
                :slug,
                :name,
              ]
            }
          }
        }
      }
  end

  def show
    service = Service.find(params[:id])
    service.update_attribute(:views, service.views+1)
    respond_with service.as_json_for_catalog
  end
end

app/views/admin/services/_form.html.haml
= simple_form_for [:admin, @service] do |f|
  = f.error_notification

  .form-inputs(ng-app='AdminTextAngular')
    = cover_uploader f
    = f.input :title
    = f.input :intro
    = text_angular_body f
    = f.input :price
    = f.association :service_category

    - if current_user.admin?
      = f.association :user, collection: User.sellers, label_method: :company_name

    = render 'attachments/images/form', f: f, images: @service.images

  .form-actions
    = f.button :submit

app/views/admin/services/edit.html.haml
%h1
  Изменение услуги
  .control-links
    = icon_link 'eye', admin_service_path(@service)

= render 'form'

app/views/admin/services/index.html.haml
%h1 Услуги

%table.table.table-striped
  %tr
    %th Название
    %th Картинка
    %th Категория
    %th

  - @services.each do |service|
    %tr
      %td= link_to service.title, admin_service_path(service)
      %td= image_tag(service.cover.thumb, class: 'img-thumbnail')
      %td= service.service_category.title
      %td
        = icon_link 'edit', edit_admin_service_path(service)
        = icon_link 'times', admin_service_path(service), data: { method: :delete, confirm: t('common.confirm_deletion') }

= paginate @services

= content_for :sidebar do
  .sidebar_panel
    = link_to 'Новая услуга', new_admin_service_path, class: 'btn btn-info'

app/views/admin/services/new.html.haml
%h1 Новая услуга

= render 'form'

app/views/admin/services/show.html.haml
- if @service.cover.present?
  = image_tag(@service.cover.large, class: 'img-thumbnail')
  %hr
%h1
  = @service.title
  .control-links
    = icon_link 'edit', edit_admin_service_path(@service)
    = icon_link 'times', admin_service_path(@service), data: { method: :delete, confirm: t('common.confirm_deletion') }
%p
  %b Введение:
  = @service.intro
%hr
%p
  %b Описание:
  = raw @service.body
%hr
%p
  %b Цена:
  = raw @service.price
%p
  %b Количество просмотров:
  = raw @service.views
%p
  %b Категория:
  = @service.service_category.title
%p
  %b Магазин:
  = @service.user.company_name

- if @service.images
  %ul
    - @service.images.each do |image|
      %li
        = image_tag(image.file.small, class: 'img-thumbnail')