config/routes.rb
Stroimarket::Application.routes.draw do

  devise_for :users

  root 'home#index'

  namespace :admin do
    root to: :index

    resources :products do
      get :custom_category_fields, on: :collection
      get :manufacturer_field, on: :collection

      resources :offers, except: [:index, :show]
    end

    resources :articles do
      post :update_position, on: :collection
    end

    resources :users do
      resources :store_profiles, except: [:index]
    end
    resources :store_profiles, only: [:index]

    resources :categories do
      post :update_position, on: :collection
    end

    resources :service_categories do
      post :update_position, on: :collection
    end

    resources :manufacturers
    resources :services
    resources :posts
  end

  namespace :api do
    resources :categories,          only: [:index, :show],  defaults: {format: :json}

    resources :stores,              only: [:index, :show],  defaults: {format: :json} do
      get :services, on: :member
    end

    resources :products,            only: [:show],          defaults: {format: :json} do
      get :popular, on: :collection
    end

    resources :service_categories,  only: [:index],         defaults: {format: :json}
    resources :services,            only: [:index, :show],  defaults: {format: :json}
    resources :posts,               only: [:index, :show],  defaults: {format: :json}
    resources :articles,            only: [:index, :show],  defaults: {format: :json}
    resources :manufacturers,       only: [:index, :show],  defaults: {format: :json}
    resources :search,              only: [:show],          defaults: {format: :json}
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

end

app/models/manufacturer.rb
class Manufacturer
  include Mongoid::Document
  include Mongoid::Search

  field :title, type: String
  field :slug, type: String

  search_in :title

  has_many :products, dependent: :nullify
  has_and_belongs_to_many :categories

  validates :title, presence: true
  validates :slug, presence: true

  before_validation :add_slug, if: :title_changed?

  private
    def add_slug
      self.slug = self.title.gsub(/['`]/, "").parameterize(sep = '_')
    end
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < AdminController
  before_action :set_manufacturer, only: [:show, :edit, :update, :destroy]

  def index
    @manufacturers = Manufacturer.all
    authorize AdminController
  end

  def show
  end

  def new
    @manufacturer = Manufacturer.new
    authorize AdminController
  end

  def edit
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    authorize AdminController

    if @manufacturer.save
      redirect_to admin_manufacturer_path(@manufacturer), notice: 'Производитель создан.'
    else
      render action: 'new'
    end
  end

  def update
    if @manufacturer.update(manufacturer_params)
      redirect_to admin_manufacturer_path(@manufacturer), notice: 'Производитель изменен.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @manufacturer.destroy
    redirect_to admin_manufacturers_path
  end

  private
    def set_manufacturer
      @manufacturer = Manufacturer.find(params[:id])
      authorize AdminController
    end

    def manufacturer_params
      params.require(:manufacturer).permit(
        :title,
        category_ids: []
      )
    end
end

app/controllers/api/manufacturers_controller.rb
class Api::ManufacturersController < ApplicationController
  respond_to :json

  def index
    manufacturers = Manufacturer.all
    respond_with manufacturers,
      except: [:_keywords]
  end

  def show
    products = Manufacturer.find(params[:id]).products
    respond_with products,
      except: [:body, :_keywords, :cover_filename, :manufacturer_id],
      methods: [:offers_count]
  end
end

app/views/admin/manufacturers/_form.html.haml
= simple_form_for [ :admin, @manufacturer ] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    -# = f.association :categories, as: :check_boxes
    = render_category_tree 'checkbox', Category.roots, 'manufacturer[category_ids][]', @manufacturer.category_ids

  .form-actions
    = f.button :submit

app/views/admin/manufacturers/edit.html.haml
%h1 Изменение производителя

= render 'form'

= link_to 'Show', admin_manufacturer_path(@manufacturer)
\|
= link_to 'Назад', admin_manufacturers_path

app/views/admin/manufacturers/index.html.haml
%h1 Производители

%table.table.table-striped
  %tr
    %th Наименование
    %th
    %th

  - @manufacturers.each do |manufacturer|
    %tr
      %td= link_to manufacturer.title, admin_manufacturer_path(manufacturer)
      %td= icon_link 'edit', edit_admin_manufacturer_path(manufacturer)
      %td= icon_link 'times', admin_manufacturer_path(manufacturer), data: { method: :delete, confirm: t('common.confirm_deletion') }

= content_for :sidebar do
  .sidebar_panel
    = link_to 'Новый производитель', new_admin_manufacturer_path, class: 'btn btn-info'

app/views/admin/manufacturers/new.html.haml
%h1 Новый произодитель

= render 'form'

= link_to 'Назад', admin_manufacturers_path

app/views/admin/manufacturers/show.html.haml
%h1
  = @manufacturer.title
  .control-links
    = icon_link 'edit', edit_admin_manufacturer_path(@manufacturer)
    = icon_link 'times', admin_manufacturer_path(@manufacturer), data: { method: :delete, confirm: t('common.confirm_deletion') }

%hr

%p
  %b slug:
  = @manufacturer.slug
%p
  = render_category_tree 'checkbox', Category.roots, 'manufacturer[category_ids][]', @manufacturer.category_ids, nil, true