config/routes.rb
Stroimarket::Application.routes.draw do

  devise_for :users

  root 'home#index'

  namespace :admin do
    root to: :index

    resources :products do
      get :custom_category_fields, on: :collection
      get :manufacturer_field, on: :collection

      resources :offers, except: [:index, :show]
    end

    resources :articles do
      post :update_position, on: :collection
    end

    resources :users do
      resources :store_profiles, except: [:index]
    end
    resources :store_profiles, only: [:index]

    resources :categories do
      post :update_position, on: :collection
    end

    resources :service_categories do
      post :update_position, on: :collection
    end

    resources :manufacturers
    resources :services
    resources :posts
  end

  namespace :api do
    resources :categories,          only: [:index, :show],  defaults: {format: :json}

    resources :stores,              only: [:index, :show],  defaults: {format: :json} do
      get :services, on: :member
    end

    resources :products,            only: [:show],          defaults: {format: :json} do
      get :popular, on: :collection
    end

    resources :service_categories,  only: [:index],         defaults: {format: :json}
    resources :services,            only: [:index, :show],  defaults: {format: :json}
    resources :posts,               only: [:index, :show],  defaults: {format: :json}
    resources :articles,            only: [:index, :show],  defaults: {format: :json}
    resources :manufacturers,       only: [:index, :show],  defaults: {format: :json}
    resources :search,              only: [:show],          defaults: {format: :json}
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

end

app/models/service_category.rb
class ServiceCategory
  include CommonCategory

  has_many :services, dependent: :destroy

end

app/controllers/admin/service_categories_controller.rb
class Admin::ServiceCategoriesController < AdminController
  include AdminPositionable

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = ServiceCategory.all
    authorize AdminController
  end

  def show
  end

  def new
    @category = ServiceCategory.new
    authorize AdminController
  end

  def edit
  end

  def create
    @category = ServiceCategory.new(category_params)
    authorize AdminController

    if @category.save
      redirect_to admin_service_categories_path, notice: 'Категория создана.'
    else
      render action: 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to admin_service_categories_path, notice: 'Категория изменена.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to admin_service_categories_path
  end

  private
    def set_category
      @category = ServiceCategory.find(params[:id])
      authorize AdminController
    end

    def category_params
      safe_attributes = [
        :title,
        :parent_id
      ]
      params.require(:service_category).permit(*safe_attributes)
    end
end

app/controllers/api/service_categories_controller.rb
class Api::ServiceCategoriesController < ApplicationController
  respond_to :json

  def index
    respond_with ServiceCategory.all,
      only: [:_id, :title, :slug],
      methods: [:slug]
  end
end

app/views/admin/service_categories/_form.html.haml
= simple_nested_form_for [ :admin, @category ] do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.association :parent

  .form-actions
    = f.button :submit

app/views/admin/service_categories/edit.html.haml
%h1
  Изменение категории услуг
  .control-links
    = icon_link 'eye', admin_service_category_path(@category)

= render 'form'

app/views/admin/service_categories/index.html.haml
%h1 Категории услуг

%ol#service_categories_root.sortable_tree.tree_root
  = render_sortable_tree @categories.roots

= content_for :sidebar do
  .sidebar_panel
    = link_to 'Новая категория', new_admin_service_category_path, class: 'btn btn-info'

app/views/admin/service_categories/new.html.haml
%h1 Новая категория

= render 'form'

app/views/admin/service_categories/show.html.haml
%h1
  = @category.title
  .control-links
    = icon_link 'edit', edit_admin_service_category_path(@category)
    = icon_link 'times', admin_service_category_path(@category), data: { method: :delete, confirm: t('common.confirm_deletion') }

%hr

%p
  %b Позиция:
  = @category.position

- if @category.parent
  %p
    %b Родительская категория:
    = @category.parent.title

- if @category.children.present?
  %p
    %b Подкатегории:
    %ol
      - @category.children.each do |child|
        %li
          =child.title