config/routes.rb
Stroimarket::Application.routes.draw do

  devise_for :users

  root 'home#index'

  namespace :admin do
    root to: :index

    resources :products do
      get :custom_category_fields, on: :collection
      get :manufacturer_field, on: :collection

      resources :offers, except: [:index, :show]
    end

    resources :articles do
      post :update_position, on: :collection
    end

    resources :users do
      resources :store_profiles, except: [:index]
    end
    resources :store_profiles, only: [:index]

    resources :categories do
      post :update_position, on: :collection
    end

    resources :service_categories do
      post :update_position, on: :collection
    end

    resources :manufacturers
    resources :services
    resources :posts
  end

  namespace :api do
    resources :categories,          only: [:index, :show],  defaults: {format: :json}

    resources :stores,              only: [:index, :show],  defaults: {format: :json} do
      get :services, on: :member
    end

    resources :products,            only: [:show],          defaults: {format: :json} do
      get :popular, on: :collection
    end

    resources :service_categories,  only: [:index],         defaults: {format: :json}
    resources :services,            only: [:index, :show],  defaults: {format: :json}
    resources :posts,               only: [:index, :show],  defaults: {format: :json}
    resources :articles,            only: [:index, :show],  defaults: {format: :json}
    resources :manufacturers,       only: [:index, :show],  defaults: {format: :json}
    resources :search,              only: [:show],          defaults: {format: :json}
  end

  get '/templates/:path.html' => 'templates#template', :constraints => { :path => /.+/  }

end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include Mongoid::Search
  include Content
  include ProductFiles

  belongs_to :category
  belongs_to :manufacturer
  belongs_to :user
  has_many :offers, dependent: :destroy

  field :min_price, type: Integer
  field :max_price, type: Integer
  field :views, type: Integer, default: 0

  before_validation :custom_field_to_datatype
  before_save :clear_old_custom_fields, if: :category_id_changed?
  validate :custom_fields_validator

  validates :category_id, :presence => true

  search_in :title

  def has_user_offer? user
    self.offers.map(&:user_id).include?(user.id)
  end

  def user_offer user
    self.offers.where(user_id: user.id)
  end

  def set_min_max_price
    update_attribute(:min_price, offers.min(:price))
    update_attribute(:max_price, offers.max(:price))
  end

  def manufacturer_title
    manufacturer.title if manufacturer?
  end

  def offers_count
    offers.count
  end

  def as_json_for_catalog
    options = {
      except: [:_id, :_keywords, :category_id, :cover_filename, :manufacturer_id, :product_images],
      include: {
        category: {
          methods: [:slug, :parents_tree],
          only: [
            :slug,
            :title,
            :parents_tree
          ],
          include: {
            product_attributes: {
              only: [:name, :title, :type, :unit]
            }
          }
        },
        offers: {
          only: [
            :price
          ],
          include: {
            user: {
              only: [:store_profile],
              include: {
                store_profile: {
                  only: [
                    :slug,
                    :name,
                    :pavilion
                  ]
                }
              }
            }
          }
        },
        manufacturer: {
          only: [
            :slug,
            :title
          ]
        },
        images: {
          only: [
            :file,
            :title
          ]
        }
      }
    }

    return serializable_hash(options)
  end

  private
    def custom_field_to_datatype
      self.category.product_attributes.each do |pr_at|
        name = pr_at.name.to_sym
        if pr_at.type == 'boolean'
          self[name] = self[name].to_bool unless self[name].is_a?(TrueClass) || self[name].is_a?(FalseClass)
        elsif pr_at.type == 'integer'
          self[name] = self[name].to_f unless self[name].is_a?(Numeric)
        end
      end
    end

    def custom_fields_validator
      max_length = 30
      max_integer = 9223372036854775807
      min_integer = -9223372036854775807

      self.category.product_attributes.each do |pr_at|
        name = pr_at.name.to_sym

        case pr_at.type
        when 'string'
          errors.add(name, "Длина строки должна быть не больше #{max_length} символов") if self[name].length > max_length
        when 'list'
          errors.add(name, "Значение должно быть одним из списка") unless JSON.parse(pr_at.unit).include? self[name]
        when 'integer'
          if self[name] > max_integer
            errors.add(name, "Значение должно быть не больше #{max_integer}")
          elsif self[name] < min_integer
            errors.add(name, "Значение должно быть не меньше #{min_integer}")
          end
        end
      end
    end

    def clear_old_custom_fields
      current = category.product_attributes.map(&:name)
      old = []
      dynamic_attributes.each do |dyn_at|
        old << dyn_at unless current.include?(dyn_at)
      end
      unset(old)
    end

    def dynamic_attributes
      attributes.keys - fields.keys
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :set_category_for_product, only: [:custom_category_fields, :manufacturer_field]

  def index
    # if current_user.admin?
    #   @products = Product.all.page(params[:page])
    # else
    #   @products = current_user.products.page(params[:page])
    # end
    @products = Product.all.page(params[:page])
    authorize @products
  end

  def show
    @product = Product.includes(:offers).find(params[:id])
    authorize @product
  end

  def new
    if current_user.admin?
      @product = Product.new
    else
      @product = current_user.products.new
    end
    authorize @product
  end

  def edit
  end

  def create
    if current_user.admin?
      @product = Product.new(product_params)
    else
      @product = current_user.products.new(product_params)
    end
    authorize @product

    if @product.save
      redirect_to admin_product_path(@product), notice: 'Товар создан.'
    else
      render action: 'new'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Товар обновлен.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path
  end

  def custom_category_fields
    render partial: "custom_category_fields", locals: {category: @category, object: @product}
  end

  def manufacturer_field
    render partial: "manufacturer_field", locals: {category: @category, object: @product}
  end

  private
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    def set_category_for_product
      if current_user.admin?
        @product = Product.find_or_initialize_by(id: params[:object_id])
      else
        @product = current_user.products.find_or_initialize_by(id: params[:object_id])
      end
      authorize @product, :update?
      @category = Category.find(params[:category_id])
    end

    def product_params
      @category = Category.find(params[:product][:category_id])

      safe_attributes = [
        :title,
        :intro,
        :body,
        :category_id,
        :cover,
        :remove_cover,
        :manufacturer_id,
        images_attributes: [
          :id,
          :title,
          :file,
          :_destroy
        ]
      ]
      safe_attributes << @category.product_attributes.map(&:name)

      params.require(:product).permit(safe_attributes)
    end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  respond_to :json

  def show
    product = Product.find(params[:id])
    product.update_attribute(:views, product.views+1)
    respond_with product.as_json_for_catalog
  end

  def popular
    products = Product.desc(:views).limit(20)
    respond_with products,
      except: [:_keywords, :cover_filename]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  after_action :verify_authorized

  def index
    if params[:query].present?
      @products = Product.full_text_search(params[:query])
    else
      @products = Product.all
    end
    authorize @products
  end

  def show
    @product = Product.includes(:offers).find(params[:id])
    authorize @product
  end

  def new
    @product = Product.new
    authorize @product
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    authorize @product

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end

  def custom_category_fields
    @product = Product.find_or_initialize_by(id: params[:object_id])
    authorize @product, :update?
    @category = Category.find(params[:category_id])

    render partial: "custom_category_fields", locals: {category: @category, object: @product}
  end

  def manufacturer_field
    @product = Product.find_or_initialize_by(id: params[:object_id])
    authorize @product, :update?
    @category = Category.find(params[:category_id])

    render partial: "manufacturer_field", locals: {category: @category, object: @product}
  end

  private
    def set_product
      @product = Product.find(params[:id])
      authorize @product
    end

    def product_params
      @category = Category.find(params[:product][:category_id])

      safe_attributes = [
        :title,
        :intro,
        :body,
        :category_id,
        :cover,
        :remove_cover,
        :manufacturer_id
      ]
      safe_attributes << @category.product_attributes.map(&:name)

      params.require(:product).permit(safe_attributes)
    end
end

app/views/admin/products/_custom_category_fields.html.haml
- if category && category.product_attributes
  = simple_fields_for(object) do |f|
    - category.product_attributes.each do |pr_at|
      = f.input pr_at.name, as: :category_attributes, type: pr_at.type, label: pr_at.title, unit: pr_at.unit

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product] do |f|
  = f.error_notification

  .form-inputs(ng-app='AdminTextAngular')
    = cover_uploader f
    = f.input :title
    = f.input :intro
    = text_angular_body f

    = render_category_tree 'radio', Category.roots, 'product[category_id]', @product.category_id, @product.id

    -# = f.association :category, input_html: {object_id: f.object._id}

    .custom_attributes
      = render partial: 'custom_category_fields', locals: {category: @product.category, object: @product}

    .manufacturer_field
      = render partial: 'manufacturer_field', locals: {category: @product.category, object: @product}

    = render 'attachments/images/form', f: f, images: @product.images

  .form-actions
    = f.button :submit

app/views/admin/products/_manufacturer_field.html.haml
- if category
  = simple_fields_for(object) do |f|
    = f.association :manufacturer, collection: category.manufacturers

app/views/admin/products/edit.html.haml
%h1
  Изменение товара
  .control-links
    = icon_link 'eye', admin_product_path(@product)

= render 'form'

app/views/admin/products/index.html.haml
%h1 Товары

%table.table.table-striped
  %tr
    %th Наименование
    %th Картинка
    %th Категория
    %th

  - @products.each do |product|
    %tr
      %td= link_to product.title, admin_product_path(product)
      %td= image_tag(product.cover.thumb, class: 'img-thumbnail')
      %td= product.category.title
      %td
        - if policy(product).update?
          = icon_link 'edit', edit_admin_product_path(product)
          = icon_link 'times', admin_product_path(product), data: { method: :delete, confirm: t('common.confirm_deletion') }

= paginate @products

= content_for :sidebar do
  .sidebar_panel
    = link_to 'Новый товар', new_admin_product_path, class: 'btn btn-info'

app/views/admin/products/new.html.haml
%h1 Новый товар

= render 'form'

app/views/admin/products/show.html.haml
- if @product.cover.present?
  = image_tag(@product.cover.large, class: 'img-thumbnail')
  %hr
%h1
  = @product.title
  - if policy(@product).update?
    .control-links
      = icon_link 'edit', edit_admin_product_path(@product)
      = icon_link 'times', admin_product_path(@product), data: { method: :delete, confirm: t('common.confirm_deletion') }
%p
  %b Введение:
  = @product.intro
%hr
%p
  %b Описание:
  = raw @product.body
%hr
%p
  %b Категория:
  = @product.category.title

- if @product.manufacturer
  %p
    %b Производитель:
    = @product.manufacturer.title

/ Часть для кастомных полей
.custom_attributes
  - if @product.category && @product.category.product_attributes
    - @product.category.product_attributes.each do |pr_at|
      %p
        %b #{pr_at.title}:
        = @product[pr_at.name]
        = pr_at.unit if pr_at.unit && pr_at.type == 'integer'
- if @product.min_price
  %p
    %b Минимальная цена:
    = @product.min_price
    = icon_ruble
  %p
    %b Максимальная цена:
    = @product.max_price
    = icon_ruble
%p
  %b Количество просмотров:
  = @product.views

- if @product.offers?
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        Цены
    %ul.list-group
      - @product.offers.each do |offer|
        %li.list-group-item
          %h4.list-group-item-heading
            = offer.price
            - if policy(offer).update?
              .control-links
                = icon_link 'edit', edit_admin_product_offer_path(@product, offer)
                = icon_link 'times', admin_product_offer_path(@product, offer), data: { method: :delete, confirm: t('common.confirm_deletion') }
          %p.list-group-item-text
            = offer.user.company_name

- if @product.images
  %ul
    - @product.images.each do |image|
      %li
        = image_tag(image.file.small, class: 'img-thumbnail')

- if current_user.admin? or not @product.has_user_offer? current_user
  = link_to 'Новая цена', new_admin_product_offer_path(@product), class: 'btn btn-primary'